version: "3.3"
services:
  app:
    build:
      args:
        user: desenvolvimento
        uid: 1000
      context: ./
      dockerfile: ./docker/Dockerfile
    image: php81
    container_name: teste-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - dev

  nginx:
    image: nginx:alpine
    container_name: teste-nginx
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - dev
    links:
      - app

  db:
    image: mysql:5.7
    restart: always
    #platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    container_name: teste-mysql
    environment:
      MYSQL_DATABASE: teste
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - /home/desenvolvimento/mysql:/var/lib/mysql
    networks:
      - dev
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - dev
    links:
      - db

networks:
  dev:
    driver: bridge
